file(WRITE ${OUTPUT_HPP} "//Auto-generated by cmake\n")
file(APPEND ${OUTPUT_HPP} "#pragma once\n")

foreach(INPUT_SHADER IN LISTS INPUT_SPVS)
    file(READ ${INPUT_SHADER}.spv SHADER_DATA HEX)
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," SHADER_DATA ${SHADER_DATA})
    get_filename_component(SHADER_NAME ${INPUT_SHADER} NAME_WE)
    get_filename_component(SHADER_TYPE ${INPUT_SHADER} EXT)
    string(REPLACE "." "" SHADER_TYPE ${SHADER_TYPE})

    file(APPEND ${OUTPUT_HPP} "\n\
namespace d2d::shaders::${SHADER_NAME} {\n\
    alignas(4) constexpr unsigned char ${SHADER_TYPE}[] = {${SHADER_DATA}}; \n\
}\n"
    )
endforeach()


