#pragma once
#include <array>
#include <vulkan/vulkan.h>


namespace d2d::vk::impl{
    constexpr std::size_t num_color_spaces = ((VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT & 0xF) + 1) + 1;
}

namespace d2d::vk::impl {
    constexpr std::array<VkColorSpaceKHR, num_color_spaces> color_space_ids = {
        VK_COLOR_SPACE_SRGB_NONLINEAR_KHR, VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT,
        VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT, VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT,
        VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT,
        VK_COLOR_SPACE_BT709_LINEAR_EXT, VK_COLOR_SPACE_BT709_NONLINEAR_EXT,
        VK_COLOR_SPACE_BT2020_LINEAR_EXT,
        VK_COLOR_SPACE_HDR10_ST2084_EXT, VK_COLOR_SPACE_DOLBYVISION_EXT, VK_COLOR_SPACE_HDR10_HLG_EXT,
        VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT, VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT,
        VK_COLOR_SPACE_PASS_THROUGH_EXT,
        VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT,
        VK_COLOR_SPACE_DISPLAY_NATIVE_AMD,
    };
}
